# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

foo <- function() {
    .Call('_scythe_foo', PACKAGE = 'scythe')
}

rcpparma_hello_world <- function() {
    .Call('_scythe_rcpparma_hello_world', PACKAGE = 'scythe')
}

rcpparma_o